#ifndef BLYNK_SECRET_CONFIG_H
#define BLYNK_SECRET_CONFIG_H

#define BLYNK_TEMPLATE_ID ""
#define BLYNK_TEMPLATE_NAME ""
#define BLYNK_AUTH_TOKEN ""
#define BLYNK_UPDATE_INTERVAL_MS 15UL * 60UL * 1000UL // 15 minutes

#endif